using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.2.1_release on 17-May-2024 14:55:40
/// Project: ASTREOS-1_OpenPOWERLINK
/// Application process for OBC_MN(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 200)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public Int16 CN1_EC_In_AI16_EC1;
		[FieldOffset(2)]
		public Int16 CN1_VALVE_In_AI16_VALVE1;
		[FieldOffset(4)]
		public Int16 CN1_VALVE_In_AI16_VALVE2;
		[FieldOffset(6)]
		public Int16 CN1_VALVE_In_AI16_VALVE3;
		[FieldOffset(8)]
		public Int16 CN1_VALVE_In_AI16_VALVE4;
		[FieldOffset(10)]
		public Int16 CN1_VALVE_In_AI16_VALVE5;
		[FieldOffset(12)]
		public Int16 CN1_VALVE_In_AI16_VALVE6;
		[FieldOffset(14)]
		public Int16 CN1_VALVE_In_AI16_VALVE7;
		[FieldOffset(16)]
		public Int16 CN1_VALVE_In_AI16_VALVE8;
		[FieldOffset(18)]
		public Int16 CN1_VALVE_In_AI16_VALVE9;
		[FieldOffset(20)]
		public Int16 CN1_VALVE_In_AI16_VALVE10;
		[FieldOffset(22)]
		public Int16 CN1_VALVE_In_AI16_VALVE11;
		[FieldOffset(24)]
		public Int16 CN1_VALVE_In_AI16_VALVE12;
		[FieldOffset(26)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(28)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(30)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(32)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(34)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(36)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(38)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(40)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(42)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(44)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(46)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(48)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(50)]
		public Int16 CN2_EC_In_AI16_EC2;
		[FieldOffset(52)]
		public Int16 CN2_VALVE_In_AI16_VALVE1;
		[FieldOffset(54)]
		public Int16 CN2_VALVE_In_AI16_VALVE2;
		[FieldOffset(56)]
		public Int16 CN2_VALVE_In_AI16_VALVE3;
		[FieldOffset(58)]
		public Int16 CN2_VALVE_In_AI16_VALVE4;
		[FieldOffset(60)]
		public Int16 CN2_VALVE_In_AI16_VALVE5;
		[FieldOffset(62)]
		public Int16 CN2_VALVE_In_AI16_VALVE6;
		[FieldOffset(64)]
		public Int16 CN2_VALVE_In_AI16_VALVE7;
		[FieldOffset(66)]
		public Int16 CN2_VALVE_In_AI16_VALVE8;
		[FieldOffset(68)]
		public Int16 CN2_VALVE_In_AI16_VALVE9;
		[FieldOffset(70)]
		public Int16 CN2_VALVE_In_AI16_VALVE10;
		[FieldOffset(72)]
		public Int16 CN2_VALVE_In_AI16_VALVE11;
		[FieldOffset(74)]
		public Int16 CN2_VALVE_In_AI16_VALVE12;
		[FieldOffset(76)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(78)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(80)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(82)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(84)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(86)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(88)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(90)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(92)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(94)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(96)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(98)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(100)]
		public Int16 CN3_EC_In_AI16_EC3;
		[FieldOffset(102)]
		public Int16 CN3_VALVE_In_AI16_VALVE1;
		[FieldOffset(104)]
		public Int16 CN3_VALVE_In_AI16_VALVE2;
		[FieldOffset(106)]
		public Int16 CN3_VALVE_In_AI16_VALVE3;
		[FieldOffset(108)]
		public Int16 CN3_VALVE_In_AI16_VALVE4;
		[FieldOffset(110)]
		public Int16 CN3_VALVE_In_AI16_VALVE5;
		[FieldOffset(112)]
		public Int16 CN3_VALVE_In_AI16_VALVE6;
		[FieldOffset(114)]
		public Int16 CN3_VALVE_In_AI16_VALVE7;
		[FieldOffset(116)]
		public Int16 CN3_VALVE_In_AI16_VALVE8;
		[FieldOffset(118)]
		public Int16 CN3_VALVE_In_AI16_VALVE9;
		[FieldOffset(120)]
		public Int16 CN3_VALVE_In_AI16_VALVE10;
		[FieldOffset(122)]
		public Int16 CN3_VALVE_In_AI16_VALVE11;
		[FieldOffset(124)]
		public Int16 CN3_VALVE_In_AI16_VALVE12;
		[FieldOffset(126)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(128)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(130)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(132)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(134)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(136)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(138)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(140)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(142)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(144)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(146)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(148)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(150)]
		public Int16 CN4_EC_In_AI16_EC4;
		[FieldOffset(152)]
		public Int16 CN4_VALVE_In_AI16_VALVE1;
		[FieldOffset(154)]
		public Int16 CN4_VALVE_In_AI16_VALVE2;
		[FieldOffset(156)]
		public Int16 CN4_VALVE_In_AI16_VALVE3;
		[FieldOffset(158)]
		public Int16 CN4_VALVE_In_AI16_VALVE4;
		[FieldOffset(160)]
		public Int16 CN4_VALVE_In_AI16_VALVE5;
		[FieldOffset(162)]
		public Int16 CN4_VALVE_In_AI16_VALVE6;
		[FieldOffset(164)]
		public Int16 CN4_VALVE_In_AI16_VALVE7;
		[FieldOffset(166)]
		public Int16 CN4_VALVE_In_AI16_VALVE8;
		[FieldOffset(168)]
		public Int16 CN4_VALVE_In_AI16_VALVE9;
		[FieldOffset(170)]
		public Int16 CN4_VALVE_In_AI16_VALVE10;
		[FieldOffset(172)]
		public Int16 CN4_VALVE_In_AI16_VALVE11;
		[FieldOffset(174)]
		public Int16 CN4_VALVE_In_AI16_VALVE12;
		[FieldOffset(176)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(178)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(180)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(182)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(184)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(186)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(188)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(190)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(192)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(194)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(196)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(198)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR12;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 104)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public Int16 CN1_EC_Out_AI16_EG;
		[FieldOffset(2)]
		public Int16 CN1_VALVE_Out_AI16_VALVE1;
		[FieldOffset(4)]
		public Int16 CN1_VALVE_Out_AI16_VALVE2;
		[FieldOffset(6)]
		public Int16 CN1_VALVE_Out_AI16_VALVE3;
		[FieldOffset(8)]
		public Int16 CN1_VALVE_Out_AI16_VALVE4;
		[FieldOffset(10)]
		public Int16 CN1_VALVE_Out_AI16_VALVE5;
		[FieldOffset(12)]
		public Int16 CN1_VALVE_Out_AI16_VALVE6;
		[FieldOffset(14)]
		public Int16 CN1_VALVE_Out_AI16_VALVE7;
		[FieldOffset(16)]
		public Int16 CN1_VALVE_Out_AI16_VALVE8;
		[FieldOffset(18)]
		public Int16 CN1_VALVE_Out_AI16_VALVE9;
		[FieldOffset(20)]
		public Int16 CN1_VALVE_Out_AI16_VALVE10;
		[FieldOffset(22)]
		public Int16 CN1_VALVE_Out_AI16_VALVE11;
		[FieldOffset(24)]
		public Int16 CN1_VALVE_Out_AI16_VALVE12;
		[FieldOffset(26)]
		public Int16 CN2_EC_Out_AI16_EG;
		[FieldOffset(28)]
		public Int16 CN2_VALVE_Out_AI16_VALVE1;
		[FieldOffset(30)]
		public Int16 CN2_VALVE_Out_AI16_VALVE2;
		[FieldOffset(32)]
		public Int16 CN2_VALVE_Out_AI16_VALVE3;
		[FieldOffset(34)]
		public Int16 CN2_VALVE_Out_AI16_VALVE4;
		[FieldOffset(36)]
		public Int16 CN2_VALVE_Out_AI16_VALVE5;
		[FieldOffset(38)]
		public Int16 CN2_VALVE_Out_AI16_VALVE6;
		[FieldOffset(40)]
		public Int16 CN2_VALVE_Out_AI16_VALVE7;
		[FieldOffset(42)]
		public Int16 CN2_VALVE_Out_AI16_VALVE8;
		[FieldOffset(44)]
		public Int16 CN2_VALVE_Out_AI16_VALVE9;
		[FieldOffset(46)]
		public Int16 CN2_VALVE_Out_AI16_VALVE10;
		[FieldOffset(48)]
		public Int16 CN2_VALVE_Out_AI16_VALVE11;
		[FieldOffset(50)]
		public Int16 CN2_VALVE_Out_AI16_VALVE12;
		[FieldOffset(52)]
		public Int16 CN3_EC_Out_AI16_EG;
		[FieldOffset(54)]
		public Int16 CN3_VALVE_Out_AI16_VALVE1;
		[FieldOffset(56)]
		public Int16 CN3_VALVE_Out_AI16_VALVE2;
		[FieldOffset(58)]
		public Int16 CN3_VALVE_Out_AI16_VALVE3;
		[FieldOffset(60)]
		public Int16 CN3_VALVE_Out_AI16_VALVE4;
		[FieldOffset(62)]
		public Int16 CN3_VALVE_Out_AI16_VALVE5;
		[FieldOffset(64)]
		public Int16 CN3_VALVE_Out_AI16_VALVE6;
		[FieldOffset(66)]
		public Int16 CN3_VALVE_Out_AI16_VALVE7;
		[FieldOffset(68)]
		public Int16 CN3_VALVE_Out_AI16_VALVE8;
		[FieldOffset(70)]
		public Int16 CN3_VALVE_Out_AI16_VALVE9;
		[FieldOffset(72)]
		public Int16 CN3_VALVE_Out_AI16_VALVE10;
		[FieldOffset(74)]
		public Int16 CN3_VALVE_Out_AI16_VALVE11;
		[FieldOffset(76)]
		public Int16 CN3_VALVE_Out_AI16_VALVE12;
		[FieldOffset(78)]
		public Int16 CN4_EC_Out_AI16_EG;
		[FieldOffset(80)]
		public Int16 CN4_VALVE_Out_AI16_VALVE1;
		[FieldOffset(82)]
		public Int16 CN4_VALVE_Out_AI16_VALVE2;
		[FieldOffset(84)]
		public Int16 CN4_VALVE_Out_AI16_VALVE3;
		[FieldOffset(86)]
		public Int16 CN4_VALVE_Out_AI16_VALVE4;
		[FieldOffset(88)]
		public Int16 CN4_VALVE_Out_AI16_VALVE5;
		[FieldOffset(90)]
		public Int16 CN4_VALVE_Out_AI16_VALVE6;
		[FieldOffset(92)]
		public Int16 CN4_VALVE_Out_AI16_VALVE7;
		[FieldOffset(94)]
		public Int16 CN4_VALVE_Out_AI16_VALVE8;
		[FieldOffset(96)]
		public Int16 CN4_VALVE_Out_AI16_VALVE9;
		[FieldOffset(98)]
		public Int16 CN4_VALVE_Out_AI16_VALVE10;
		[FieldOffset(100)]
		public Int16 CN4_VALVE_Out_AI16_VALVE11;
		[FieldOffset(102)]
		public Int16 CN4_VALVE_Out_AI16_VALVE12;
	}

}
