using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.2.1_release on 21-May-2024 15:51:09
/// Project: ASTREOS-1_OpenPOWERLINK
/// Application process for OBC_MN(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 552)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public Int16 CN1_EC_In_AI16_EC1;
		[FieldOffset(2)]
		public Int16 CN1_VALVE_In_AI16_VALVE1;
		[FieldOffset(4)]
		public Int16 CN1_VALVE_In_AI16_VALVE2;
		[FieldOffset(6)]
		public Int16 CN1_VALVE_In_AI16_VALVE3;
		[FieldOffset(8)]
		public Int16 CN1_VALVE_In_AI16_VALVE4;
		[FieldOffset(10)]
		public Int16 CN1_VALVE_In_AI16_VALVE5;
		[FieldOffset(12)]
		public Int16 CN1_VALVE_In_AI16_VALVE6;
		[FieldOffset(14)]
		public Int16 CN1_VALVE_In_AI16_VALVE7;
		[FieldOffset(16)]
		public Int16 CN1_VALVE_In_AI16_VALVE8;
		[FieldOffset(18)]
		public Int16 CN1_VALVE_In_AI16_VALVE9;
		[FieldOffset(20)]
		public Int16 CN1_VALVE_In_AI16_VALVE10;
		[FieldOffset(22)]
		public Int16 CN1_VALVE_In_AI16_VALVE11;
		[FieldOffset(24)]
		public Int16 CN1_VALVE_In_AI16_VALVE12;
		[FieldOffset(26)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(28)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(30)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(32)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(34)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(36)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(38)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(40)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(42)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(44)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(46)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(48)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(50)]
		public Int16 CN2_EC_In_AI16_EC2;
		[FieldOffset(52)]
		public Int16 CN2_VALVE_In_AI16_VALVE1;
		[FieldOffset(54)]
		public Int16 CN2_VALVE_In_AI16_VALVE2;
		[FieldOffset(56)]
		public Int16 CN2_VALVE_In_AI16_VALVE3;
		[FieldOffset(58)]
		public Int16 CN2_VALVE_In_AI16_VALVE4;
		[FieldOffset(60)]
		public Int16 CN2_VALVE_In_AI16_VALVE5;
		[FieldOffset(62)]
		public Int16 CN2_VALVE_In_AI16_VALVE6;
		[FieldOffset(64)]
		public Int16 CN2_VALVE_In_AI16_VALVE7;
		[FieldOffset(66)]
		public Int16 CN2_VALVE_In_AI16_VALVE8;
		[FieldOffset(68)]
		public Int16 CN2_VALVE_In_AI16_VALVE9;
		[FieldOffset(70)]
		public Int16 CN2_VALVE_In_AI16_VALVE10;
		[FieldOffset(72)]
		public Int16 CN2_VALVE_In_AI16_VALVE11;
		[FieldOffset(74)]
		public Int16 CN2_VALVE_In_AI16_VALVE12;
		[FieldOffset(76)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(78)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(80)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(82)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(84)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(86)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(88)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(90)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(92)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(94)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(96)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(98)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(100)]
		public Int16 CN3_EC_In_AI16_EC3;
		[FieldOffset(102)]
		public Int16 CN3_VALVE_In_AI16_VALVE1;
		[FieldOffset(104)]
		public Int16 CN3_VALVE_In_AI16_VALVE2;
		[FieldOffset(106)]
		public Int16 CN3_VALVE_In_AI16_VALVE3;
		[FieldOffset(108)]
		public Int16 CN3_VALVE_In_AI16_VALVE4;
		[FieldOffset(110)]
		public Int16 CN3_VALVE_In_AI16_VALVE5;
		[FieldOffset(112)]
		public Int16 CN3_VALVE_In_AI16_VALVE6;
		[FieldOffset(114)]
		public Int16 CN3_VALVE_In_AI16_VALVE7;
		[FieldOffset(116)]
		public Int16 CN3_VALVE_In_AI16_VALVE8;
		[FieldOffset(118)]
		public Int16 CN3_VALVE_In_AI16_VALVE9;
		[FieldOffset(120)]
		public Int16 CN3_VALVE_In_AI16_VALVE10;
		[FieldOffset(122)]
		public Int16 CN3_VALVE_In_AI16_VALVE11;
		[FieldOffset(124)]
		public Int16 CN3_VALVE_In_AI16_VALVE12;
		[FieldOffset(126)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(128)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(130)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(132)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(134)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(136)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(138)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(140)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(142)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(144)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(146)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(148)]
		public Int16 CN3_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(150)]
		public Int16 CN4_EC_In_AI16_EC4;
		[FieldOffset(152)]
		public Int16 CN4_VALVE_In_AI16_VALVE1;
		[FieldOffset(154)]
		public Int16 CN4_VALVE_In_AI16_VALVE2;
		[FieldOffset(156)]
		public Int16 CN4_VALVE_In_AI16_VALVE3;
		[FieldOffset(158)]
		public Int16 CN4_VALVE_In_AI16_VALVE4;
		[FieldOffset(160)]
		public Int16 CN4_VALVE_In_AI16_VALVE5;
		[FieldOffset(162)]
		public Int16 CN4_VALVE_In_AI16_VALVE6;
		[FieldOffset(164)]
		public Int16 CN4_VALVE_In_AI16_VALVE7;
		[FieldOffset(166)]
		public Int16 CN4_VALVE_In_AI16_VALVE8;
		[FieldOffset(168)]
		public Int16 CN4_VALVE_In_AI16_VALVE9;
		[FieldOffset(170)]
		public Int16 CN4_VALVE_In_AI16_VALVE10;
		[FieldOffset(172)]
		public Int16 CN4_VALVE_In_AI16_VALVE11;
		[FieldOffset(174)]
		public Int16 CN4_VALVE_In_AI16_VALVE12;
		[FieldOffset(176)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(178)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(180)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(182)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(184)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(186)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(188)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(190)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(192)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(194)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(196)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(198)]
		public Int16 CN4_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(200)]
		public Int16 CN5_EC_In_AI16_EC5;
		[FieldOffset(202)]
		public Int16 CN5_VALVE_In_AI16_VALVE1;
		[FieldOffset(204)]
		public Int16 CN5_VALVE_In_AI16_VALVE2;
		[FieldOffset(206)]
		public Int16 CN5_VALVE_In_AI16_VALVE3;
		[FieldOffset(208)]
		public Int16 CN5_VALVE_In_AI16_VALVE4;
		[FieldOffset(210)]
		public Int16 CN5_VALVE_In_AI16_VALVE5;
		[FieldOffset(212)]
		public Int16 CN5_VALVE_In_AI16_VALVE6;
		[FieldOffset(214)]
		public Int16 CN5_VALVE_In_AI16_VALVE7;
		[FieldOffset(216)]
		public Int16 CN5_VALVE_In_AI16_VALVE8;
		[FieldOffset(218)]
		public Int16 CN5_VALVE_In_AI16_VALVE9;
		[FieldOffset(220)]
		public Int16 CN5_VALVE_In_AI16_VALVE10;
		[FieldOffset(222)]
		public Int16 CN5_VALVE_In_AI16_VALVE11;
		[FieldOffset(224)]
		public Int16 CN5_VALVE_In_AI16_VALVE12;
		[FieldOffset(226)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(228)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(230)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(232)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(234)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(236)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(238)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(240)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(242)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(244)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(246)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(248)]
		public Int16 CN5_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(250)]
		public Int16 CN6_EC_In_AI16_EC6;
		[FieldOffset(252)]
		public Int16 CN6_VALVE_In_AI16_VALVE1;
		[FieldOffset(254)]
		public Int16 CN6_VALVE_In_AI16_VALVE2;
		[FieldOffset(256)]
		public Int16 CN6_VALVE_In_AI16_VALVE3;
		[FieldOffset(258)]
		public Int16 CN6_VALVE_In_AI16_VALVE4;
		[FieldOffset(260)]
		public Int16 CN6_VALVE_In_AI16_VALVE5;
		[FieldOffset(262)]
		public Int16 CN6_VALVE_In_AI16_VALVE6;
		[FieldOffset(264)]
		public Int16 CN6_VALVE_In_AI16_VALVE7;
		[FieldOffset(266)]
		public Int16 CN6_VALVE_In_AI16_VALVE8;
		[FieldOffset(268)]
		public Int16 CN6_VALVE_In_AI16_VALVE9;
		[FieldOffset(270)]
		public Int16 CN6_VALVE_In_AI16_VALVE10;
		[FieldOffset(272)]
		public Int16 CN6_VALVE_In_AI16_VALVE11;
		[FieldOffset(274)]
		public Int16 CN6_VALVE_In_AI16_VALVE12;
		[FieldOffset(276)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(278)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(280)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(282)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(284)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(286)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(288)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(290)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(292)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(294)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(296)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(298)]
		public Int16 CN6_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(300)]
		public Int16 CN7_EC_In_AI16_EC7;
		[FieldOffset(302)]
		public Int16 CN7_VALVE_In_AI16_VALVE1;
		[FieldOffset(304)]
		public Int16 CN7_VALVE_In_AI16_VALVE2;
		[FieldOffset(306)]
		public Int16 CN7_VALVE_In_AI16_VALVE3;
		[FieldOffset(308)]
		public Int16 CN7_VALVE_In_AI16_VALVE4;
		[FieldOffset(310)]
		public Int16 CN7_VALVE_In_AI16_VALVE5;
		[FieldOffset(312)]
		public Int16 CN7_VALVE_In_AI16_VALVE6;
		[FieldOffset(314)]
		public Int16 CN7_VALVE_In_AI16_VALVE7;
		[FieldOffset(316)]
		public Int16 CN7_VALVE_In_AI16_VALVE8;
		[FieldOffset(318)]
		public Int16 CN7_VALVE_In_AI16_VALVE9;
		[FieldOffset(320)]
		public Int16 CN7_VALVE_In_AI16_VALVE10;
		[FieldOffset(322)]
		public Int16 CN7_VALVE_In_AI16_VALVE11;
		[FieldOffset(324)]
		public Int16 CN7_VALVE_In_AI16_VALVE12;
		[FieldOffset(326)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(328)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(330)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(332)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(334)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(336)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(338)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(340)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(342)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(344)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(346)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(348)]
		public Int16 CN7_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(350)]
		public Int16 CN8_EC_In_AI16_EC8;
		[FieldOffset(352)]
		public Int16 CN8_VALVE_In_AI16_VALVE1;
		[FieldOffset(354)]
		public Int16 CN8_VALVE_In_AI16_VALVE2;
		[FieldOffset(356)]
		public Int16 CN8_VALVE_In_AI16_VALVE3;
		[FieldOffset(358)]
		public Int16 CN8_VALVE_In_AI16_VALVE4;
		[FieldOffset(360)]
		public Int16 CN8_VALVE_In_AI16_VALVE5;
		[FieldOffset(362)]
		public Int16 CN8_VALVE_In_AI16_VALVE6;
		[FieldOffset(364)]
		public Int16 CN8_VALVE_In_AI16_VALVE7;
		[FieldOffset(366)]
		public Int16 CN8_VALVE_In_AI16_VALVE8;
		[FieldOffset(368)]
		public Int16 CN8_VALVE_In_AI16_VALVE9;
		[FieldOffset(370)]
		public Int16 CN8_VALVE_In_AI16_VALVE10;
		[FieldOffset(372)]
		public Int16 CN8_VALVE_In_AI16_VALVE11;
		[FieldOffset(374)]
		public Int16 CN8_VALVE_In_AI16_VALVE12;
		[FieldOffset(376)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(378)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(380)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(382)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(384)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(386)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(388)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(390)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(392)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(394)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(396)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(398)]
		public Int16 CN8_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(400)]
		public Int16 CN9_EC_In_AI16_EC9;
		[FieldOffset(402)]
		public Int16 CN9_VALVE_In_AI16_VALVE1;
		[FieldOffset(404)]
		public Int16 CN9_VALVE_In_AI16_VALVE2;
		[FieldOffset(406)]
		public Int16 CN9_VALVE_In_AI16_VALVE3;
		[FieldOffset(408)]
		public Int16 CN9_VALVE_In_AI16_VALVE4;
		[FieldOffset(410)]
		public Int16 CN9_VALVE_In_AI16_VALVE5;
		[FieldOffset(412)]
		public Int16 CN9_VALVE_In_AI16_VALVE6;
		[FieldOffset(414)]
		public Int16 CN9_VALVE_In_AI16_VALVE7;
		[FieldOffset(416)]
		public Int16 CN9_VALVE_In_AI16_VALVE8;
		[FieldOffset(418)]
		public Int16 CN9_VALVE_In_AI16_VALVE9;
		[FieldOffset(420)]
		public Int16 CN9_VALVE_In_AI16_VALVE10;
		[FieldOffset(422)]
		public Int16 CN9_VALVE_In_AI16_VALVE11;
		[FieldOffset(424)]
		public Int16 CN9_VALVE_In_AI16_VALVE12;
		[FieldOffset(426)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(428)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(430)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(432)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(434)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(436)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(438)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(440)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(442)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(444)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(446)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(448)]
		public Int16 CN9_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(450)]
		public Int16 CN10_EC_In_AI16_EC10;
		[FieldOffset(452)]
		public Int16 CN10_VALVE_In_AI16_VALVE1;
		[FieldOffset(454)]
		public Int16 CN10_VALVE_In_AI16_VALVE2;
		[FieldOffset(456)]
		public Int16 CN10_VALVE_In_AI16_VALVE3;
		[FieldOffset(458)]
		public Int16 CN10_VALVE_In_AI16_VALVE4;
		[FieldOffset(460)]
		public Int16 CN10_VALVE_In_AI16_VALVE5;
		[FieldOffset(462)]
		public Int16 CN10_VALVE_In_AI16_VALVE6;
		[FieldOffset(464)]
		public Int16 CN10_VALVE_In_AI16_VALVE7;
		[FieldOffset(466)]
		public Int16 CN10_VALVE_In_AI16_VALVE8;
		[FieldOffset(468)]
		public Int16 CN10_VALVE_In_AI16_VALVE9;
		[FieldOffset(470)]
		public Int16 CN10_VALVE_In_AI16_VALVE10;
		[FieldOffset(472)]
		public Int16 CN10_VALVE_In_AI16_VALVE11;
		[FieldOffset(474)]
		public Int16 CN10_VALVE_In_AI16_VALVE12;
		[FieldOffset(476)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(478)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(480)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(482)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(484)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(486)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(488)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(490)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(492)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(494)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(496)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(498)]
		public Int16 CN10_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(500)]
		public Int16 CN11_EC_In_AI16_EC11;
		[FieldOffset(502)]
		public Int16 CN11_VALVE_In_AI16_VALVE1;
		[FieldOffset(504)]
		public Int16 CN11_VALVE_In_AI16_VALVE2;
		[FieldOffset(506)]
		public Int16 CN11_VALVE_In_AI16_VALVE3;
		[FieldOffset(508)]
		public Int16 CN11_VALVE_In_AI16_VALVE4;
		[FieldOffset(510)]
		public Int16 CN11_VALVE_In_AI16_VALVE5;
		[FieldOffset(512)]
		public Int16 CN11_VALVE_In_AI16_VALVE6;
		[FieldOffset(514)]
		public Int16 CN11_VALVE_In_AI16_VALVE7;
		[FieldOffset(516)]
		public Int16 CN11_VALVE_In_AI16_VALVE8;
		[FieldOffset(518)]
		public Int16 CN11_VALVE_In_AI16_VALVE9;
		[FieldOffset(520)]
		public Int16 CN11_VALVE_In_AI16_VALVE10;
		[FieldOffset(522)]
		public Int16 CN11_VALVE_In_AI16_VALVE11;
		[FieldOffset(524)]
		public Int16 CN11_VALVE_In_AI16_VALVE12;
		[FieldOffset(526)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(528)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(530)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(532)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(534)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(536)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(538)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(540)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(542)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(544)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(546)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(548)]
		public Int16 CN11_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(550)]
		public byte PADDING_VAR_1;
		[FieldOffset(551)]
		public byte PADDING_VAR_2;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 288)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public Int16 CN1_EC_Out_AI16_EG;
		[FieldOffset(2)]
		public Int16 CN1_VALVE_Out_AI16_VALVE1;
		[FieldOffset(4)]
		public Int16 CN1_VALVE_Out_AI16_VALVE2;
		[FieldOffset(6)]
		public Int16 CN1_VALVE_Out_AI16_VALVE3;
		[FieldOffset(8)]
		public Int16 CN1_VALVE_Out_AI16_VALVE4;
		[FieldOffset(10)]
		public Int16 CN1_VALVE_Out_AI16_VALVE5;
		[FieldOffset(12)]
		public Int16 CN1_VALVE_Out_AI16_VALVE6;
		[FieldOffset(14)]
		public Int16 CN1_VALVE_Out_AI16_VALVE7;
		[FieldOffset(16)]
		public Int16 CN1_VALVE_Out_AI16_VALVE8;
		[FieldOffset(18)]
		public Int16 CN1_VALVE_Out_AI16_VALVE9;
		[FieldOffset(20)]
		public Int16 CN1_VALVE_Out_AI16_VALVE10;
		[FieldOffset(22)]
		public Int16 CN1_VALVE_Out_AI16_VALVE11;
		[FieldOffset(24)]
		public Int16 CN1_VALVE_Out_AI16_VALVE12;
		[FieldOffset(26)]
		public Int16 CN2_EC_Out_AI16_EG;
		[FieldOffset(28)]
		public Int16 CN2_VALVE_Out_AI16_VALVE1;
		[FieldOffset(30)]
		public Int16 CN2_VALVE_Out_AI16_VALVE2;
		[FieldOffset(32)]
		public Int16 CN2_VALVE_Out_AI16_VALVE3;
		[FieldOffset(34)]
		public Int16 CN2_VALVE_Out_AI16_VALVE4;
		[FieldOffset(36)]
		public Int16 CN2_VALVE_Out_AI16_VALVE5;
		[FieldOffset(38)]
		public Int16 CN2_VALVE_Out_AI16_VALVE6;
		[FieldOffset(40)]
		public Int16 CN2_VALVE_Out_AI16_VALVE7;
		[FieldOffset(42)]
		public Int16 CN2_VALVE_Out_AI16_VALVE8;
		[FieldOffset(44)]
		public Int16 CN2_VALVE_Out_AI16_VALVE9;
		[FieldOffset(46)]
		public Int16 CN2_VALVE_Out_AI16_VALVE10;
		[FieldOffset(48)]
		public Int16 CN2_VALVE_Out_AI16_VALVE11;
		[FieldOffset(50)]
		public Int16 CN2_VALVE_Out_AI16_VALVE12;
		[FieldOffset(52)]
		public Int16 CN3_EC_Out_AI16_EG;
		[FieldOffset(54)]
		public Int16 CN3_VALVE_Out_AI16_VALVE1;
		[FieldOffset(56)]
		public Int16 CN3_VALVE_Out_AI16_VALVE2;
		[FieldOffset(58)]
		public Int16 CN3_VALVE_Out_AI16_VALVE3;
		[FieldOffset(60)]
		public Int16 CN3_VALVE_Out_AI16_VALVE4;
		[FieldOffset(62)]
		public Int16 CN3_VALVE_Out_AI16_VALVE5;
		[FieldOffset(64)]
		public Int16 CN3_VALVE_Out_AI16_VALVE6;
		[FieldOffset(66)]
		public Int16 CN3_VALVE_Out_AI16_VALVE7;
		[FieldOffset(68)]
		public Int16 CN3_VALVE_Out_AI16_VALVE8;
		[FieldOffset(70)]
		public Int16 CN3_VALVE_Out_AI16_VALVE9;
		[FieldOffset(72)]
		public Int16 CN3_VALVE_Out_AI16_VALVE10;
		[FieldOffset(74)]
		public Int16 CN3_VALVE_Out_AI16_VALVE11;
		[FieldOffset(76)]
		public Int16 CN3_VALVE_Out_AI16_VALVE12;
		[FieldOffset(78)]
		public Int16 CN4_EC_Out_AI16_EG;
		[FieldOffset(80)]
		public Int16 CN4_VALVE_Out_AI16_VALVE1;
		[FieldOffset(82)]
		public Int16 CN4_VALVE_Out_AI16_VALVE2;
		[FieldOffset(84)]
		public Int16 CN4_VALVE_Out_AI16_VALVE3;
		[FieldOffset(86)]
		public Int16 CN4_VALVE_Out_AI16_VALVE4;
		[FieldOffset(88)]
		public Int16 CN4_VALVE_Out_AI16_VALVE5;
		[FieldOffset(90)]
		public Int16 CN4_VALVE_Out_AI16_VALVE6;
		[FieldOffset(92)]
		public Int16 CN4_VALVE_Out_AI16_VALVE7;
		[FieldOffset(94)]
		public Int16 CN4_VALVE_Out_AI16_VALVE8;
		[FieldOffset(96)]
		public Int16 CN4_VALVE_Out_AI16_VALVE9;
		[FieldOffset(98)]
		public Int16 CN4_VALVE_Out_AI16_VALVE10;
		[FieldOffset(100)]
		public Int16 CN4_VALVE_Out_AI16_VALVE11;
		[FieldOffset(102)]
		public Int16 CN4_VALVE_Out_AI16_VALVE12;
		[FieldOffset(104)]
		public Int16 CN5_EC_Out_AI16_EG;
		[FieldOffset(106)]
		public Int16 CN5_VALVE_Out_AI16_VALVE1;
		[FieldOffset(108)]
		public Int16 CN5_VALVE_Out_AI16_VALVE2;
		[FieldOffset(110)]
		public Int16 CN5_VALVE_Out_AI16_VALVE3;
		[FieldOffset(112)]
		public Int16 CN5_VALVE_Out_AI16_VALVE4;
		[FieldOffset(114)]
		public Int16 CN5_VALVE_Out_AI16_VALVE5;
		[FieldOffset(116)]
		public Int16 CN5_VALVE_Out_AI16_VALVE6;
		[FieldOffset(118)]
		public Int16 CN5_VALVE_Out_AI16_VALVE7;
		[FieldOffset(120)]
		public Int16 CN5_VALVE_Out_AI16_VALVE8;
		[FieldOffset(122)]
		public Int16 CN5_VALVE_Out_AI16_VALVE9;
		[FieldOffset(124)]
		public Int16 CN5_VALVE_Out_AI16_VALVE10;
		[FieldOffset(126)]
		public Int16 CN5_VALVE_Out_AI16_VALVE11;
		[FieldOffset(128)]
		public Int16 CN5_VALVE_Out_AI16_VALVE12;
		[FieldOffset(130)]
		public Int16 CN6_EC_Out_AI16_EG;
		[FieldOffset(132)]
		public Int16 CN6_VALVE_Out_AI16_VALVE1;
		[FieldOffset(134)]
		public Int16 CN6_VALVE_Out_AI16_VALVE2;
		[FieldOffset(136)]
		public Int16 CN6_VALVE_Out_AI16_VALVE3;
		[FieldOffset(138)]
		public Int16 CN6_VALVE_Out_AI16_VALVE4;
		[FieldOffset(140)]
		public Int16 CN6_VALVE_Out_AI16_VALVE5;
		[FieldOffset(142)]
		public Int16 CN6_VALVE_Out_AI16_VALVE6;
		[FieldOffset(144)]
		public Int16 CN6_VALVE_Out_AI16_VALVE7;
		[FieldOffset(146)]
		public Int16 CN6_VALVE_Out_AI16_VALVE8;
		[FieldOffset(148)]
		public Int16 CN6_VALVE_Out_AI16_VALVE9;
		[FieldOffset(150)]
		public Int16 CN6_VALVE_Out_AI16_VALVE10;
		[FieldOffset(152)]
		public Int16 CN6_VALVE_Out_AI16_VALVE11;
		[FieldOffset(154)]
		public Int16 CN6_VALVE_Out_AI16_VALVE12;
		[FieldOffset(156)]
		public Int16 CN7_EC_Out_AI16_EG;
		[FieldOffset(158)]
		public Int16 CN7_VALVE_Out_AI16_VALVE1;
		[FieldOffset(160)]
		public Int16 CN7_VALVE_Out_AI16_VALVE2;
		[FieldOffset(162)]
		public Int16 CN7_VALVE_Out_AI16_VALVE3;
		[FieldOffset(164)]
		public Int16 CN7_VALVE_Out_AI16_VALVE4;
		[FieldOffset(166)]
		public Int16 CN7_VALVE_Out_AI16_VALVE5;
		[FieldOffset(168)]
		public Int16 CN7_VALVE_Out_AI16_VALVE6;
		[FieldOffset(170)]
		public Int16 CN7_VALVE_Out_AI16_VALVE7;
		[FieldOffset(172)]
		public Int16 CN7_VALVE_Out_AI16_VALVE8;
		[FieldOffset(174)]
		public Int16 CN7_VALVE_Out_AI16_VALVE9;
		[FieldOffset(176)]
		public Int16 CN7_VALVE_Out_AI16_VALVE10;
		[FieldOffset(178)]
		public Int16 CN7_VALVE_Out_AI16_VALVE11;
		[FieldOffset(180)]
		public Int16 CN7_VALVE_Out_AI16_VALVE12;
		[FieldOffset(182)]
		public Int16 CN8_EC_Out_AI16_EG;
		[FieldOffset(184)]
		public Int16 CN8_VALVE_Out_AI16_VALVE1;
		[FieldOffset(186)]
		public Int16 CN8_VALVE_Out_AI16_VALVE2;
		[FieldOffset(188)]
		public Int16 CN8_VALVE_Out_AI16_VALVE3;
		[FieldOffset(190)]
		public Int16 CN8_VALVE_Out_AI16_VALVE4;
		[FieldOffset(192)]
		public Int16 CN8_VALVE_Out_AI16_VALVE5;
		[FieldOffset(194)]
		public Int16 CN8_VALVE_Out_AI16_VALVE6;
		[FieldOffset(196)]
		public Int16 CN8_VALVE_Out_AI16_VALVE7;
		[FieldOffset(198)]
		public Int16 CN8_VALVE_Out_AI16_VALVE8;
		[FieldOffset(200)]
		public Int16 CN8_VALVE_Out_AI16_VALVE9;
		[FieldOffset(202)]
		public Int16 CN8_VALVE_Out_AI16_VALVE10;
		[FieldOffset(204)]
		public Int16 CN8_VALVE_Out_AI16_VALVE11;
		[FieldOffset(206)]
		public Int16 CN8_VALVE_Out_AI16_VALVE12;
		[FieldOffset(208)]
		public Int16 CN9_EC_Out_AI16_EG;
		[FieldOffset(210)]
		public Int16 CN9_VALVE_Out_AI16_VALVE1;
		[FieldOffset(212)]
		public Int16 CN9_VALVE_Out_AI16_VALVE2;
		[FieldOffset(214)]
		public Int16 CN9_VALVE_Out_AI16_VALVE3;
		[FieldOffset(216)]
		public Int16 CN9_VALVE_Out_AI16_VALVE4;
		[FieldOffset(218)]
		public Int16 CN9_VALVE_Out_AI16_VALVE5;
		[FieldOffset(220)]
		public Int16 CN9_VALVE_Out_AI16_VALVE6;
		[FieldOffset(222)]
		public Int16 CN9_VALVE_Out_AI16_VALVE7;
		[FieldOffset(224)]
		public Int16 CN9_VALVE_Out_AI16_VALVE8;
		[FieldOffset(226)]
		public Int16 CN9_VALVE_Out_AI16_VALVE9;
		[FieldOffset(228)]
		public Int16 CN9_VALVE_Out_AI16_VALVE10;
		[FieldOffset(230)]
		public Int16 CN9_VALVE_Out_AI16_VALVE11;
		[FieldOffset(232)]
		public Int16 CN9_VALVE_Out_AI16_VALVE12;
		[FieldOffset(234)]
		public Int16 CN10_EC_Out_AI16_EG;
		[FieldOffset(236)]
		public Int16 CN10_VALVE_Out_AI16_VALVE1;
		[FieldOffset(238)]
		public Int16 CN10_VALVE_Out_AI16_VALVE2;
		[FieldOffset(240)]
		public Int16 CN10_VALVE_Out_AI16_VALVE3;
		[FieldOffset(242)]
		public Int16 CN10_VALVE_Out_AI16_VALVE4;
		[FieldOffset(244)]
		public Int16 CN10_VALVE_Out_AI16_VALVE5;
		[FieldOffset(246)]
		public Int16 CN10_VALVE_Out_AI16_VALVE6;
		[FieldOffset(248)]
		public Int16 CN10_VALVE_Out_AI16_VALVE7;
		[FieldOffset(250)]
		public Int16 CN10_VALVE_Out_AI16_VALVE8;
		[FieldOffset(252)]
		public Int16 CN10_VALVE_Out_AI16_VALVE9;
		[FieldOffset(254)]
		public Int16 CN10_VALVE_Out_AI16_VALVE10;
		[FieldOffset(256)]
		public Int16 CN10_VALVE_Out_AI16_VALVE11;
		[FieldOffset(258)]
		public Int16 CN10_VALVE_Out_AI16_VALVE12;
		[FieldOffset(260)]
		public Int16 CN11_EC_Out_AI16_EG;
		[FieldOffset(262)]
		public Int16 CN11_VALVE_Out_AI16_VALVE1;
		[FieldOffset(264)]
		public Int16 CN11_VALVE_Out_AI16_VALVE2;
		[FieldOffset(266)]
		public Int16 CN11_VALVE_Out_AI16_VALVE3;
		[FieldOffset(268)]
		public Int16 CN11_VALVE_Out_AI16_VALVE4;
		[FieldOffset(270)]
		public Int16 CN11_VALVE_Out_AI16_VALVE5;
		[FieldOffset(272)]
		public Int16 CN11_VALVE_Out_AI16_VALVE6;
		[FieldOffset(274)]
		public Int16 CN11_VALVE_Out_AI16_VALVE7;
		[FieldOffset(276)]
		public Int16 CN11_VALVE_Out_AI16_VALVE8;
		[FieldOffset(278)]
		public Int16 CN11_VALVE_Out_AI16_VALVE9;
		[FieldOffset(280)]
		public Int16 CN11_VALVE_Out_AI16_VALVE10;
		[FieldOffset(282)]
		public Int16 CN11_VALVE_Out_AI16_VALVE11;
		[FieldOffset(284)]
		public Int16 CN11_VALVE_Out_AI16_VALVE12;
		[FieldOffset(286)]
		public byte PADDING_VAR_1;
		[FieldOffset(287)]
		public byte PADDING_VAR_2;
	}

}
