using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.2.1_release on 17-May-2024 16:17:06
/// Project: ASTREOS-1_OpenPOWERLINK
/// Application process for OBC_MN(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 52)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public Int16 CN1_EC_In_AI16_EC1;
		[FieldOffset(2)]
		public Int16 CN1_VALVE_In_AI16_VALVE1;
		[FieldOffset(4)]
		public Int16 CN1_VALVE_In_AI16_VALVE2;
		[FieldOffset(6)]
		public Int16 CN1_VALVE_In_AI16_VALVE3;
		[FieldOffset(8)]
		public Int16 CN1_VALVE_In_AI16_VALVE4;
		[FieldOffset(10)]
		public Int16 CN1_VALVE_In_AI16_VALVE5;
		[FieldOffset(12)]
		public Int16 CN1_VALVE_In_AI16_VALVE6;
		[FieldOffset(14)]
		public Int16 CN1_VALVE_In_AI16_VALVE7;
		[FieldOffset(16)]
		public Int16 CN1_VALVE_In_AI16_VALVE8;
		[FieldOffset(18)]
		public Int16 CN1_VALVE_In_AI16_VALVE9;
		[FieldOffset(20)]
		public Int16 CN1_VALVE_In_AI16_VALVE10;
		[FieldOffset(22)]
		public Int16 CN1_VALVE_In_AI16_VALVE11;
		[FieldOffset(24)]
		public Int16 CN1_VALVE_In_AI16_VALVE12;
		[FieldOffset(26)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(28)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(30)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(32)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(34)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(36)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(38)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(40)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(42)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(44)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(46)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(48)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(50)]
		public byte PADDING_VAR_1;
		[FieldOffset(51)]
		public byte PADDING_VAR_2;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 28)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public Int16 CN1_EC_Out_AI16_EG;
		[FieldOffset(2)]
		public Int16 CN1_VALVE_Out_AI16_VALVE1;
		[FieldOffset(4)]
		public Int16 CN1_VALVE_Out_AI16_VALVE2;
		[FieldOffset(6)]
		public Int16 CN1_VALVE_Out_AI16_VALVE3;
		[FieldOffset(8)]
		public Int16 CN1_VALVE_Out_AI16_VALVE4;
		[FieldOffset(10)]
		public Int16 CN1_VALVE_Out_AI16_VALVE5;
		[FieldOffset(12)]
		public Int16 CN1_VALVE_Out_AI16_VALVE6;
		[FieldOffset(14)]
		public Int16 CN1_VALVE_Out_AI16_VALVE7;
		[FieldOffset(16)]
		public Int16 CN1_VALVE_Out_AI16_VALVE8;
		[FieldOffset(18)]
		public Int16 CN1_VALVE_Out_AI16_VALVE9;
		[FieldOffset(20)]
		public Int16 CN1_VALVE_Out_AI16_VALVE10;
		[FieldOffset(22)]
		public Int16 CN1_VALVE_Out_AI16_VALVE11;
		[FieldOffset(24)]
		public Int16 CN1_VALVE_Out_AI16_VALVE12;
		[FieldOffset(26)]
		public byte PADDING_VAR_1;
		[FieldOffset(27)]
		public byte PADDING_VAR_2;
	}

}
