using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.2.1_release on 17-May-2024 16:16:23
/// Project: ASTREOS-1_OpenPOWERLINK
/// Application process for OBC_MN(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 100)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public Int16 CN1_EC_In_AI16_EC1;
		[FieldOffset(2)]
		public Int16 CN1_VALVE_In_AI16_VALVE1;
		[FieldOffset(4)]
		public Int16 CN1_VALVE_In_AI16_VALVE2;
		[FieldOffset(6)]
		public Int16 CN1_VALVE_In_AI16_VALVE3;
		[FieldOffset(8)]
		public Int16 CN1_VALVE_In_AI16_VALVE4;
		[FieldOffset(10)]
		public Int16 CN1_VALVE_In_AI16_VALVE5;
		[FieldOffset(12)]
		public Int16 CN1_VALVE_In_AI16_VALVE6;
		[FieldOffset(14)]
		public Int16 CN1_VALVE_In_AI16_VALVE7;
		[FieldOffset(16)]
		public Int16 CN1_VALVE_In_AI16_VALVE8;
		[FieldOffset(18)]
		public Int16 CN1_VALVE_In_AI16_VALVE9;
		[FieldOffset(20)]
		public Int16 CN1_VALVE_In_AI16_VALVE10;
		[FieldOffset(22)]
		public Int16 CN1_VALVE_In_AI16_VALVE11;
		[FieldOffset(24)]
		public Int16 CN1_VALVE_In_AI16_VALVE12;
		[FieldOffset(26)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(28)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(30)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(32)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(34)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(36)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(38)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(40)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(42)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(44)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(46)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(48)]
		public Int16 CN1_SENSOR_In_AI16_SENSOR12;
		[FieldOffset(50)]
		public Int16 CN2_EC_In_AI16_EC2;
		[FieldOffset(52)]
		public Int16 CN2_VALVE_In_AI16_VALVE1;
		[FieldOffset(54)]
		public Int16 CN2_VALVE_In_AI16_VALVE2;
		[FieldOffset(56)]
		public Int16 CN2_VALVE_In_AI16_VALVE3;
		[FieldOffset(58)]
		public Int16 CN2_VALVE_In_AI16_VALVE4;
		[FieldOffset(60)]
		public Int16 CN2_VALVE_In_AI16_VALVE5;
		[FieldOffset(62)]
		public Int16 CN2_VALVE_In_AI16_VALVE6;
		[FieldOffset(64)]
		public Int16 CN2_VALVE_In_AI16_VALVE7;
		[FieldOffset(66)]
		public Int16 CN2_VALVE_In_AI16_VALVE8;
		[FieldOffset(68)]
		public Int16 CN2_VALVE_In_AI16_VALVE9;
		[FieldOffset(70)]
		public Int16 CN2_VALVE_In_AI16_VALVE10;
		[FieldOffset(72)]
		public Int16 CN2_VALVE_In_AI16_VALVE11;
		[FieldOffset(74)]
		public Int16 CN2_VALVE_In_AI16_VALVE12;
		[FieldOffset(76)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR1;
		[FieldOffset(78)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR2;
		[FieldOffset(80)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR3;
		[FieldOffset(82)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR4;
		[FieldOffset(84)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR5;
		[FieldOffset(86)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR6;
		[FieldOffset(88)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR7;
		[FieldOffset(90)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR8;
		[FieldOffset(92)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR9;
		[FieldOffset(94)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR10;
		[FieldOffset(96)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR11;
		[FieldOffset(98)]
		public Int16 CN2_SENSOR_In_AI16_SENSOR12;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 52)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public Int16 CN1_EC_Out_AI16_EG;
		[FieldOffset(2)]
		public Int16 CN1_VALVE_Out_AI16_VALVE1;
		[FieldOffset(4)]
		public Int16 CN1_VALVE_Out_AI16_VALVE2;
		[FieldOffset(6)]
		public Int16 CN1_VALVE_Out_AI16_VALVE3;
		[FieldOffset(8)]
		public Int16 CN1_VALVE_Out_AI16_VALVE4;
		[FieldOffset(10)]
		public Int16 CN1_VALVE_Out_AI16_VALVE5;
		[FieldOffset(12)]
		public Int16 CN1_VALVE_Out_AI16_VALVE6;
		[FieldOffset(14)]
		public Int16 CN1_VALVE_Out_AI16_VALVE7;
		[FieldOffset(16)]
		public Int16 CN1_VALVE_Out_AI16_VALVE8;
		[FieldOffset(18)]
		public Int16 CN1_VALVE_Out_AI16_VALVE9;
		[FieldOffset(20)]
		public Int16 CN1_VALVE_Out_AI16_VALVE10;
		[FieldOffset(22)]
		public Int16 CN1_VALVE_Out_AI16_VALVE11;
		[FieldOffset(24)]
		public Int16 CN1_VALVE_Out_AI16_VALVE12;
		[FieldOffset(26)]
		public Int16 CN2_EC_Out_AI16_EG;
		[FieldOffset(28)]
		public Int16 CN2_VALVE_Out_AI16_VALVE1;
		[FieldOffset(30)]
		public Int16 CN2_VALVE_Out_AI16_VALVE2;
		[FieldOffset(32)]
		public Int16 CN2_VALVE_Out_AI16_VALVE3;
		[FieldOffset(34)]
		public Int16 CN2_VALVE_Out_AI16_VALVE4;
		[FieldOffset(36)]
		public Int16 CN2_VALVE_Out_AI16_VALVE5;
		[FieldOffset(38)]
		public Int16 CN2_VALVE_Out_AI16_VALVE6;
		[FieldOffset(40)]
		public Int16 CN2_VALVE_Out_AI16_VALVE7;
		[FieldOffset(42)]
		public Int16 CN2_VALVE_Out_AI16_VALVE8;
		[FieldOffset(44)]
		public Int16 CN2_VALVE_Out_AI16_VALVE9;
		[FieldOffset(46)]
		public Int16 CN2_VALVE_Out_AI16_VALVE10;
		[FieldOffset(48)]
		public Int16 CN2_VALVE_Out_AI16_VALVE11;
		[FieldOffset(50)]
		public Int16 CN2_VALVE_Out_AI16_VALVE12;
	}

}
